server:
  port: 8080
spring:
  application:
    name: student
  datasource:
    username: 'unforgettabledew'
    password: '27092100'
    url: jdbc:postgresql://localhost:5432/student
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
details-service: DETAILS
